language: generic
matrix:
  include:
    - script:
        - make test
        - pod lib lint
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.3
      before_install:
        - pod repo update
    - script:
        - swift test
        - swiftlint
      env: JOB=SPM
      os: osx
      osx_image: xcode8.3
    - script: make docker_test
      env: JOB=Linux-Swift3.1
      sudo: required
      services: docker
    - script: make docker_test_4
      env: JOB=Linux-Swift4
      sudo: required
      services: docker
    - script: swift test
      env: JOB=Linux-Swift4-without-Docker
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libblocksruntime0
      install:
        - export SWIFT_VERSION=swift-4.0-DEVELOPMENT-SNAPSHOT-2017-05-11-a
        - >
          curl https://swift.org/builds/swift-4.0-branch/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
          | tar xz --directory $HOME --strip-components=1
        - export PATH=$HOME/usr/bin:$PATH
        - export LINUX_SOURCEKIT_LIB_PATH=$HOME/usr/lib
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
