aliases:
  - &steps-for-xcode
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: make bootstrap
      - run: xcodebuild -workspace SourceKitten.xcworkspace -scheme sourcekitten $XCODE_FLAGS test|xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - run: echo "ruby-2.3" > ~/.ruby-version
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
      - run: bundle exec pod lib lint

  - &steps-for-swiftpm
    - checkout
    - run: git submodule update --init --recursive
    - run: swift test
    - run: brew install swiftlint && swiftlint lint --strict

  - &steps-for-linux
    - checkout
    - run: swift test

version: 2
jobs:

  xcode_9:
    macos:
      xcode: "9.0"
    <<: *steps-for-xcode

  swiftpm_4:
    macos:
      xcode: "9.0"
    steps: *steps-for-swiftpm

  linux_swift_4:
    docker:
      - image: norionomura/swift:40
    steps: *steps-for-linux

  xcode_9.1:
    macos:
      xcode: "9.1.0"
    <<: *steps-for-xcode

  swiftpm_4.0.2:
    macos:
      xcode: "9.1.0"
    steps: *steps-for-swiftpm

  linux_swift_4.0.2:
    docker:
      - image: norionomura/swift:402
    steps: *steps-for-linux

  xcode_9.2:
    macos:
      xcode: "9.2.0"
    <<: *steps-for-xcode

  swiftpm_4.0.3:
    macos:
      xcode: "9.2.0"
    steps: *steps-for-swiftpm

  linux_swift_4.0.3:
    docker:
      - image: norionomura/swift:403
    steps: *steps-for-linux

  xcode_9.3:
    macos:
      xcode: "9.3.0"
    <<: *steps-for-xcode

  swiftpm_4.1:
    macos:
      xcode: "9.3.0"
    steps: *steps-for-swiftpm

  linux_swift_4.1:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps: *steps-for-linux

  xcode_10.0:
    macos:
      xcode: "10.0.0"
    environment:
      XCODE_FLAGS: -parallel-testing-enabled NO
    <<: *steps-for-xcode

  swiftpm_4.2:
    macos:
      xcode: "10.0.0"
    steps: *steps-for-swiftpm

  linux_swift_4.2:
    docker:
      - image: norionomura/swift:4220180730a
    steps: *steps-for-linux

workflows:
  version: 2
  workflow:
    jobs:
      - xcode_9
      - swiftpm_4
      - linux_swift_4
      - xcode_9.1
      - swiftpm_4.0.2
      - linux_swift_4.0.2
      - xcode_9.2
      - swiftpm_4.0.3
      - linux_swift_4.0.3
      - xcode_9.3
      - swiftpm_4.1
      - linux_swift_4.1
      - xcode_10.0
      - swiftpm_4.2
      - linux_swift_4.2
