version: 2
jobs:

  xcode_9:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: pod repo update
      - run: make test|xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - restore_cache:
          key: cocoapods
      - run: pod lib lint
      - save_cache:
          key: cocoapods
          paths:
            - ~/.cocoapods

  swiftpm_4:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: swift test
      - run: brew install swiftlint && swiftlint lint --strict

  linux_swift_4:
    docker:
      - image: norionomura/swift:40
    steps:
      - checkout
      - run: swift test

  xcode_9.1:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: pod repo update
      - run: make test|xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - restore_cache:
          key: cocoapods
      - run: pod lib lint
      - save_cache:
          key: cocoapods
          paths:
            - ~/.cocoapods

  swiftpm_4.0.2:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: swift test
      - run: brew install swiftlint && swiftlint lint --strict

  linux_swift_4.0.2:
    docker:
      - image: norionomura/swift:402
    steps:
      - checkout
      - run: swift test

  xcode_9.2:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: pod repo update
      - run: make test|xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - restore_cache:
          key: cocoapods
      - run: pod lib lint
      - save_cache:
          key: cocoapods
          paths:
            - ~/.cocoapods

  swiftpm_4.0.3:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: swift test
      - run: brew install swiftlint && swiftlint lint --strict

  linux_swift_4.0.3:
    docker:
      - image: norionomura/swift:403
    steps:
      - checkout
      - run: swift test

workflows:
  version: 2
  workflow:
    jobs:
      - xcode_9
      - swiftpm_4
      - linux_swift_4
      - xcode_9.1
      - swiftpm_4.0.2
      - linux_swift_4.0.2
      - xcode_9.2
      - swiftpm_4.0.3
      - linux_swift_4.0.3
